### ISSUE TITLE
Create client toggle for highlight vs outline

### ISSUE THREAD

**Issue by lee0c** [billba/excitation#73]
There's pros and cons to both highlights and outlines. We probably want a user experience where they can be switched back and forth, and possibly customized in color (though that might happen at organization level, not user level).

**Comment by billba** [comment]
This isn't really about user or company _preferences_. It's about "I can't see a blue outline on this page/document that happens to be dominated by blue boxes."

**Comment by billba** [comment]
Covered by #44
